/*
    Generated by entity generator. Should only be edited in generator files
*/

package ${extensionPackage};

import ${nmsName};
import ${craftName};

public class ${entityName} extends Ex${superNmsName} {

    public ${entityName}(${craftName} entity) {
        super(entity);
    }

    public ${entityName}(${nmsName} entity) {
        super(entity);
    }
}
