/*
    Generated by entity generator. Should only be edited in generator files
*/

package ${moduleName};

<#include "ExEntityImports.ftl">

@NmsReflection
public class ${entityName} extends ${craftName} implements EntityExtension<${extensionEntity.getName()}> {

    public ${entityName}(World world) {
        super(((CraftServer) Bukkit.getServer()), new ${nmsName}(EntityTypes.${nmsTypeName}, ((CraftWorld) world).getHandle()));
    }

<#include "ExEntityExtension.ftl">

}