/*
    Generated by entity generator. Should only be edited in generator files
*/

package ${moduleName};

<#include "ExEntityImports.ftl">

@NmsReflection
public class ${entityName} extends ${craftName} implements EntityExtension<${extensionEntity.getName()}> {

    public ${entityName}(World world, boolean loadDefaultPathfinders) {
        super(((CraftServer) Bukkit.getServer()), new ${nmsName}(EntityTypes.${nmsTypeName},
                ((CraftWorld) world).getHandle()) {
            @Override
            public void u() {
                if (loadDefaultPathfinders) {
                    super.u();
                }
            }
        });
    }

<#include "ExEntityExtension.ftl">

}